### ISSUE TITLE
World Stones to Cobble Conversion

### ISSUE THREAD

**Issue by dragonshardz** [dragonshardz/dpt7#13]
- [x] Create recipe for converting world stones that don't drop a cobblestone variant
- [x] Add world stones as needed to the `quark:stone_tool_materials` tag

**Comment by neogeo0823** [comment]
This one's solved, but needs tweaking for specific materials. I'll add the code into the main branch, but this isn't solved till that tweaking happens. 

Relevant bits of code are:

placed in the global vars section:
`var basestone = <tag:items:forge:stone>;`

placed under the rawFishesArray, and is the bit that needs tweaking:
```
val worldStoneArray = [
	<item:minecraft:stone>,
	<item:minecraft:granite>,
	<item:minecraft:diorite>,
	<item:minecraft:andesite>,
	<item:minecraft:mossy_cobblestone>,
	<item:create:limestone>,
	<item:create:granite_cobblestone>,
	<item:create:diorite_cobblestone>,
	<item:create:andesite_cobblestone>,
	<item:create:limestone_cobblestone>,
	<item:create:diorite_cobblestone>,
	<item:create:weathered_limestone>,
	<item:create:weathered_limestone_cobblestone>,
	<item:create:dolomite>,
	<item:create:dolomite_cobblestone>,
	<item:create:gabbro>,
	<item:create:gabbro_cobblestone>,
	<item:create:scoria>,
	<item:create:scoria_cobblestone>,
	<item:create:dark_scoria>,
	<item:create:dark_scoria_cobblestone>,
	<item:quark:permafrost>,
	<item:quark:cobbedstone>,
	<item:quark:marble>,
	<item:quark:limestone>,
	<item:quark:jasper>,
	<item:quark:slate>,
	<item:quark:basalt>,
	<item:quark:myalite>,
	
] as IItemStack[];

for item in worldStoneArray{
	basestone.add(item);
}
```

and finally, placed in the new recipes section, and could maybe be refined?:
`craftingTable.addShapeless("cobbledcobble", <item:minecraft:cobblestone> * 8, [basestone, basestone, basestone, basestone, basestone, basestone, basestone, basestone, basestone], null);`

**Comment by neogeo0823** [comment]
added list provided by Johnny to the misc.zs worldStoneArray. Code is as follows:

```
	<item:minecraft:blackstone>,
	<item:atmospheric:smooth_arid_sandstone>,
	<item:atmospheric:smooth_red_arid_sandstone>,
	<item:atmospheric:arid_sand>,
	<item:atmospheric:red_arid_sand>,
	<item:biomesoplenty:white_sand>,
	<item:biomesoplenty:smooth_white_sandstone>,
	<item:create:gabbro>,
	<item:create:dolomite>,
	<item:create:limestone>,
	<item:create:weathered_limestone>,
	<item:create:scoria>,
	<item:create:limesand>,
	<item:engineersdecor:dense_grit_dirt>
```

**Comment by neogeo0823** [comment]
Added code to misc.zs that added all items in worldStoneArray to the quark stone tool materials tag. Code is as follows:
```
<quark:stone_tool_materials>.add(item);
```
