### ISSUE TITLE
add ability to fill milk bottles in Create spout

### ISSUE THREAD

**Issue by dragonshardz** [dragonshardz/dpt7#20]

**Comment by neogeo0823** [comment]
code for this is as follows:

//new create recipes
<recipetype:create:filling>.addRecipe("fill_milk_bottle", <item:farmersdelight:milk_bottle>, <item:minecraft:glass_bottle>, <fluid:create:milk> * 333);

Will output 1 milk bottle from farmers delight when 1 glass bottle is placed under the spout and the spout is filled with at least 333mb of milk.

**Comment by neogeo0823** [comment]
updated food.zs
