### ISSUE TITLE
Modify IE conveyor recipes

### ISSUE THREAD

**Issue by dragonshardz** [dragonshardz/dpt7#3]
- [x] Remove recipes for all IE conveyors
- [x] Add a new recipe that converts 2 Create shafts and a leather belt into 4 plain IE conveyors

**Comment by neogeo0823** [comment]
This.... seems done? the normal plain conveyor recipe is gone, and the new one is in. Shouldn't it be marked done?

**Comment by dragonshardz** [comment]
The purpose is to remove the recipes for all of the IE conveyor types not needed for IE multiblocks, to center Create (and technically the Simple Storage Network) as the primary method of item transport.

**Comment by neogeo0823** [comment]
this is done. code will be commited to machines.zs, as follows:

in new section: recipe removal:
```
val removeMachineArray = [
 "immersiveengineering:crafting/conveyor_redstone",
	"immersiveengineering:crafting/conveyor_dropper",
	"immersiveengineering:crafting/conveyor_vertical",
	"immersiveengineering:crafting/conveyor_splitter",
	"immersiveengineering:crafting/conveyor_extract",
	"immersiveengineering:crafting/conveyor_covered",
	"immersiveengineering:crafting/conveyor_droppercovered",
	"immersiveengineering:crafting/conveyor_verticalcovered",
	"immersiveengineering:crafting/conveyor_extractcovered",
	"immersiveengineering:crafting/conveyor_splittercovered"
  ] as string[];

for str in removeMachineArray{
    craftingTable.removeByName(str);
}
```
