### ISSUE TITLE
Adjust wheat-based food recipes

### ISSUE THREAD

**Issue by dragonshardz** [dragonshardz/dpt7#8]
To encourage taking advantage of more efficient output of Create milling/crushing

- [x] Remove/adjust extraneous vanilla Cake recipes
- [x] Yucca Gateau to use 1 dough and 1 less yucca fruit
- [x] Raw Pasta to use 1 flour and 1 egg
- [x] Pancake uses 1 flour
- [x] Honey Cookie, Sweet Berry Cookie, and vanilla cookie combine 1 dough and 1 honey bottle/sweet berry/cocoa bean
- [x] Pie crust is milk and dough
- [x] Remove wheat from apple pie recipe
- [x] Add barley to same tag group as wheat for cross-compat
- [x] Add cross-usage tags to FD and PHCFC pasta

**Comment by neogeo0823** [comment]
committed code for yucca gateau and raw pasta tasks. detailed what was changed in the commit description.

**Comment by neogeo0823** [comment]
ok, got a lot done. Fixed the recipes for cakes, pancakes, the cookies, and the pie crust. changes are detailed below.

under recipe removal

```
	"autumnity:pancake"
	"farmersdelight:cake_from_milk_bottle",
	"minecraft:cake",
	"ceramics:cake"
	"minecraft:cookie",
	"quark:tweaks/crafting/utility/bent/cookie",
	"farmersdelight:sweet_berry_cookie",
	"farmersdelight:honey_cookie",
	"farmersdelight:pie_crust",
	"farmersdelight:integration/create/mixing/pie_crust_from_mixing"
```

below recipe removal is a new section, 

```//remove create recipes
<recipetype:create:mixing>.removeRecipe(<item:farmersdelight:pie_crust>);
```

under the new recipes section
```
craftingTable.addShapeless("autpancake", <item:autumnity:pancake>, [egg,flour,milk,syrup], null);

craftingTable.addShaped("doughcake", <item:minecraft:cake>, [[milk, milk, milk], [<tag:items:forge:sugar>, egg, <tag:items:forge:sugar>], [dough, <item:minecraft:air>, dough]], null);

craftingTable.addShapeless("doughcookie", <item:minecraft:cookie>, [dough,cbeans], null);

craftingTable.addShapeless("sweetcookie", <item:farmersdelight:sweet_berry_cookie>, [dough, <item:minecraft:sweet_berries>], null);

craftingTable.addShapeless("honeycookie", <item:farmersdelight:honey_cookie>, [dough,honeybottle], null);

craftingTable.addShapeless("fdpiecrust", <item:farmersdelight:pie_crust>, [dough, milk, dough], null);
```
under create recipes
```
<recipetype:create:mechanical_crafting>.addRecipe("cookiecraft", <item:minecraft:cookie>, [[dough, cbeans]]);

<recipetype:create:mechanical_crafting>.addRecipe("fdpiecrust", <item:farmersdelight:pie_crust>, [[dough, milk, dough]]);

<recipetype:create:mixing>.addRecipe("mix_pie_crust", "none", <item:farmersdelight:pie_crust, [dough, milk, dough]);
```

The above code will be merged with the main branch.

**Comment by neogeo0823** [comment]
ok, finished up this task. 

The last one, about unifying pastas, they both have identical recipes by default, but the recipes don't seem to use the forge tag for specifying the ingredients, so the icons don't swap back and forth when you view the recipes. So, no real action needed there, I guess, unless you wanna remake 11 recipes just for the sake of visual unity.

for everything else, changes are as follows:

for machines.zs, I will be committing the following:

Added new create mech. crafter recipe for FD apple pie, code as follows:
```
<recipetype:create:mechanical_crafting>.addRecipe("createfdapplepie", <item:farmersdelight:apple_pie>, [[<item:minecraft:air>, dough, <item:minecraft:air>], [<item:minecraft:apple>, <item:minecraft:apple>, <item:minecraft:apple>], [<tag:items:forge:sugar>, <item:farmersdelight:pie_crust>, <tag:items:forge:sugar>]]);
```

and for food.zs, the following changes:

removed stock recipes for FD apple pie, added shaped crafting for new recipe. code as follows:

In removed recipes:
```
"farmersdelight:apple_pie"
```
in new recipes:
```
craftingTable.addShaped("fdapplepie", <item:farmersdelight:apple_pie>, [[<item:minecraft:air>, dough, <item:minecraft:air>], [<item:minecraft:apple>, <item:minecraft:apple>, <item:minecraft:apple>], [<tag:items:forge:sugar>, <item:farmersdelight:pie_crust>, <tag:items:forge:sugar>]], null);
```

Added Barley to tags:items:forge:flour_plants, to allow it to be made into flour. code as follows:

in global vars:
```
var flourplants = <tag:items:forge:flour_plants>;
```
in tag additions:
```
flourplants.add(<item:biomesoplenty:barley>);
```
